model: "mbt2018-mean"
dataset_path: "/vimeo_test_clean"
epochs: 100
batch_size: 32
learning_rate: 1e-4
aux_learning_rate: 1e-3
lmbda: 0.08
num_workers: 4
clip_max_norm: 0.1
seed: 42
use_cuda: true
checkpoint_dir: "checkpoints"
save_interval: 10